// vue/资料/代码/day18/src/views/film/HotFilm.vue
<template>
  <van-list
    v-model:loading="loading"
    :finished="finished"
    finished-text="没有更多了"
  >
    <van-cell v-for="item in films" :key="item.filmId">
      <div style="display: flex;align-items:center">
        <van-image width="66" height="92" :src="item.poster" />
        <div style="width: 200px">
          {{ item.name }}
        </div>
        <van-button plain color="#ff5f16" size="small">收藏</van-button>
      </div>
    </van-cell>
  </van-list>
</template>

<script setup>
import http from "../../utils/request";
import { onMounted, reactive,ref } from "vue";
const loading = ref(false);
const finished = ref(false);
var films = reactive([]);
onMounted(() => {
  http
    .get("/gateway", {
      params: {
        cityId: "330100",
        pageNum: 1,
        pageSize: 10,
        type: 1,
        k: "5691835",
      },
    })
    .then((res) => {
      // reactive在此处修改值时不能直接赋值,会改变数据类型
      films.push(...res.data.data.films);
    });
});
</script>

<style lang="scss" scoped>
</style>

// react/资料/day7/src/views/film/HotFilm.jsx
import React, { Component } from 'react';
import http from '../../utils/request'
import './hotFilm.css'
import {add_film} from '../../store/actions'
import {connect} from 'react-redux'
class HotFilm extends Component {

    state={
        films:[]
    }

    componentDidMount(){
        http.get("/?cityId=330100&pageNum=1&pageSize=10&type=1&k=368546").then(res=>{
            this.setState({
                films:res.data.data.films
            })
        })
    }
    render() {

        return (
            <>
                <ul className='film-list'>
                    {
                        this.state.films.map(item=>{
                            return  (<li key={item.filmId} style={{margin:"10px auto"}}>
                                <img src={item.poster} alt="" width={66}/>
                                <p>
                                    {item.name}
                                </p>
                                <button onClick={()=>{
                                    // store.dispatch(add_film(item))
                                    this.props.add_collect_film(item)
                                }}>收藏</button>
                            </li>)
                        })
                    }
                </ul>
            </>
        );
    }
}

export default connect(
    ()=>{
        return {

        }
    },
    (dispatch)=>{
        return {
            add_collect_film:(film)=>{
                dispatch(add_film(film))
            }
        }
    }
)(HotFilm);
