// react/资料/day11/Home.jsx
import React, { useEffect,useState } from 'react';
import { connect } from 'react-redux'
import { Layout, Avatar, Tooltip, Menu } from 'antd';
import { RadarChartOutlined,OrderedListOutlined } from '@ant-design/icons';
import './home.scss'
import { PoweroffOutlined } from '@ant-design/icons';
import http from '../utils/request'
const { Sider, Content } = Layout;
function Home(props) {

    let [items,setItems]=useState([])

    let logout = () => {
        sessionStorage.removeItem("current_user");
        props.clear_current_user();
        props.history.push("/login")
    }

    let getIcon=(name)=>{
        switch(name){
            case "RadarChartOutlined":
                return <RadarChartOutlined/>;
            case "OrderedListOutlined":
                return <OrderedListOutlined/>
        }
    }

    useEffect(() => {
        http.get("/sysUser/getUserMenus", {
            params: {
                userId: props.currentUser.id
            }
        }).then(res => {
            let menus=[]
            res.data.object.forEach(({name,id,icon,children})=>{
                let childs=[]
                children.forEach(({name,id,icon})=>{
                    childs.push(getItem(name,id,getIcon(icon)))
                })                
                menus.push(getItem(name,id,getIcon(icon),childs))
            })
            console.log(menus);
            setItems(menus)
        })
    }, [])


    const [openKeys, setOpenKeys] = useState(['sub1']);
    const onOpenChange = (keys) => {
        const latestOpenKey = keys.find((key) => openKeys.indexOf(key) === -1);
        if (rootSubmenuKeys.indexOf(latestOpenKey) === -1) {
            setOpenKeys(keys);
        } else {
            setOpenKeys(latestOpenKey ? [latestOpenKey] : []);
        }
    };
    const rootSubmenuKeys = ['sub1', 'sub2', 'sub4'];

    function getItem(label, key, icon, children, type) {
        return {
            key,
            icon,
            children,
            label,
            type,
        };
    }

    
    return (
        <Layout>
            <Sider>
                <h1>好教练后台管理系统</h1>
                <Avatar size={64} src={props.currentUser.avatarUrl} />
                <p>欢迎您,{props.currentUser.nickName}
                    <Tooltip placement="top" title={"点击退出"}><PoweroffOutlined onClick={logout} /></Tooltip>
                </p>

                <Menu
                    mode="inline"
                    openKeys={openKeys}
                    onOpenChange={onOpenChange}
                    items={items}
                />
            </Sider>
            <Content>Content</Content>
        </Layout>
    );
}

export default connect(
    (state) => {
        return {
            currentUser: state.currentUser
        }
    },
    (dispatch) => {
        return {
            clear_current_user: () => {
                dispatch({ type: "CLEAR_CURRENT_USER" })
            }
        }
    }
)(Home);

// vue/资料/代码/day12/Home.vue
<template>
  <el-container>
    <el-aside width="200px">
      <h1>浙江车检检汽车服务有限公司</h1>
      <el-avatar
        src="https://cartest.zjcjj.net/logo.png"
        :size="80"
      ></el-avatar>
      <p>
        欢迎您,{{ currentUser.username }}
        <el-tooltip
          class="item"
          effect="dark"
          content="点击退出"
          placement="top"
        >
          <i class="el-icon-switch-button" @click="logOut"></i>
        </el-tooltip>
      </p>

      <el-menu
        default-active="2"
        class="el-menu-vertical-demo"
        @open="handleOpen"
        @close="handleClose"
      >
        <el-submenu :index="'/home'+item.path" v-for="item in menus" :key="item.path">
          <template slot="title">
            <i :class="item.icon"></i>
            <span>{{item.name}}</span>
          </template>

          <el-menu-item :index="subitem.path" v-for="subitem in item.children" :key="subitem.path"> <i :class="subitem.icon"></i> {{subitem.name}}</el-menu-item>

        </el-submenu>
        
      </el-menu>
    </el-aside>
    <el-main>Main</el-main>
  </el-container>
</template>

<script>
import { mapState, mapMutations } from "vuex";
export default {
  name: "HomeView",
  components: {},
  data:function(){
    return {
      menus:[]
    }
  },
  computed: {
    ...mapState(["currentUser"]),
  },
  mounted:function(){
    this.$http.post("/sysUser/getUserMenus",this.currentUser).then(res=>{
      this.menus=res.data.object;
    })
  },
  methods: {
    ...mapMutations(["clear_current_user"]),
    logOut: function () {
      this.clear_current_user();
      sessionStorage.removeItem("currentUser");
      this.$router.push("/login");
    },
    handleOpen(key, keyPath) {
      console.log(key, keyPath);
    },
    handleClose(key, keyPath) {
      console.log(key, keyPath);
    },
  },
};
</script>
<style lang="scss">
.el-container {
  background: #f6fafd;
  height: 100%;
  .el-aside {
    box-shadow: 0px 0px 40px 0px rgba(2, 25, 35, 0.1);
    padding: 0 12px;
    h1 {
      margin-top: 30px;
      text-align: center;
      font-size: 20px;
      font-family: PingFangSC;
      font-weight: 500;
      color: #333;
    }
    .el-avatar {
      margin: 32px 0 20px;
    }
    .el-menu {
      border: none;
      margin-top: 20px;
    }
  }
}
</style>
