// vue/资料/代码/day8/src/views/films/HotFilm.vue
<template>
    <FilmList :films="films"></FilmList>
</template>

<script>
import axios from 'axios'
import FilmList from '../../components/FilmList.vue'
export default {
    components:{
        FilmList
    },
    data:function(){
        return {
            films:[]
        }
    },
    mounted:function(){
        axios.defaults.headers['X-host']="mall.film-ticket.film.list";
        axios.get("https://m.maizuo.com/gateway?cityId=330100&pageNum=1&pageSize=10&type=1&k=368546").then(res=>{
            this.films=res.data.data.films;
        })
    }
}
</script>

<style>
.poster{
    width:66px;
    height:92px;
}
</style>

// react/资料/day6/src/views/film/HotFilm.jsx
import React, { Component } from 'react';
import http from '../../utils/request'
import './hotFilm.css'
class HotFilm extends Component {

    state={
        films:[]
    }

    componentDidMount(){
        http.get("/?cityId=330100&pageNum=1&pageSize=10&type=1&k=368546").then(res=>{
            this.setState({
                films:res.data.data.films
            })
        })
    }
    render() {

        return (
            <>
                <ul className='film-list'>
                    {
                        this.state.films.map(item=>{
                            return  (<li key={item.filmId}>
                                <img src={item.poster} alt="" width={66}/>
                                <p>
                                    {item.name}
                                </p>
                            </li>)
                        })
                    }
                </ul>
            </>
        );
    }
}

export default HotFilm;
