// react/资料/day19/src/views/Login.jsx
import React from 'react';
import './login.scss'
import {
    Image, Form,
    Input,
    Button,
    Checkbox,
    Toast
} from 'antd-mobile'
import http from '../utils/request'
import { connect } from 'react-redux'
import { useNavigate } from 'react-router-dom'
function Login(props) {
    let navigate = useNavigate();
    const onFinish = (values) => {
        // Dialog.alert({
        //     content: <pre>{JSON.stringify(values, null, 2)}</pre>,
        // })
        http.post("/driverUser/login", values).then(res => {
            if (res.data.code) {
                sessionStorage.setItem("currentUser", JSON.stringify(res.data.object));
                props.init_current_user(res.data.object)

                Toast.show({
                    icon: 'success',
                    content: res.data.message,
                })

                navigate("/home")
            } else {
                Toast.show({
                    icon: 'fail',
                    content: res.data.message,
                })
            }
        })
    }

    return (
        <div className='container'>
            <Image src={require("../static/logo.png")} width={256} fit='fill' />

            <Form
                name='form'
                onFinish={onFinish}
                layout='horizontal'
                footer={
                    <Button block type='submit' color='primary' size='large'>
                        提交
                    </Button>
                }
            >
                <Form.Item name='account' label='账户' rules={[{ required: true }]}>
                    <Input placeholder='请输入账户' />
                </Form.Item>
                <Form.Item name='password' label='密码' rules={[{ required: true }]}>
                    <Input placeholder='请输入密码' type={"password"} />
                </Form.Item>
                <Form.Item name='protocol' rules={[{ required: true, message: "请勾选服务协议" }]}>
                    <Checkbox>我已阅读并同意该条款<a className='protocol' href="https://zjcjj.net/protocol/">《服务协议》</a></Checkbox>
                </Form.Item>
            </Form>
        </div>
    );
}

export default connect(
    () => {
        return {}
    },
    (dispatch) => {
        return {
            init_current_user: (user) => {
                dispatch({ type: "INIT_CURRENT_USER", user })
            }
        }
    }
)(Login);

// vue/code/day12/cjj/src/views/Login.vue
<template>
  <div class="login" @keypress.enter="submit">
    <div class="container">
      <!--  图-->
      <el-image
          style="width: 100px; height: 100px"
          src="https://cartest.zjcjj.net/logo.png"></el-image>
      <!-- 表单-->
      <el-form :model="loginForm" :rules="rules" ref="loginForm">
        <el-form-item prop="account">
          <el-input placeholder="请输入账户" prefix-icon="el-icon-user"
                    v-model="loginForm.account"></el-input>
        </el-form-item>

        <el-form-item prop="password">
          <el-input placeholder="请输入密码" prefix-icon="el-icon-lock"
                    v-model="loginForm.password" show-password></el-input>
        </el-form-item>

        <el-form-item>
          <el-button type="primary" @click="submit">登录</el-button>
          <el-button type="text">重置</el-button>
        </el-form-item>
      </el-form>

    </div>

  </div>
</template>

<script>
import {mapMutations} from "vuex";

export default {
  data() {
    return {
      loginForm: {},
      rules: {
        account: [
          {required: true, message: '请输入账户', trigger: 'blur'},
          {min: 5, max: 15, message: '长度在 5 到 15 个字符', trigger: 'blur'}
        ],
        password: [
          {required: true, message: '请输入密码', trigger: 'blur'},
          {min: 5, max: 15, message: '长度在 5 到 15 个字符', trigger: 'blur'}
        ],
      }
    };
  },
  methods: {
    ...mapMutations(["init_current_users"]),
    submit() {
      // console.log( this.$refs.loginForm)
      //element-ui上摘下来
      this.$refs.loginForm.validate((valid) => {
        //如果符合规范就返回true ,反之false
        // console.log(valid)
        if (valid) {
          // 提交数据到后台
          this.$http.post("/sysUser/login", this.loginForm).then(res => {
            console.log(res)
            if (res.data.code) {
              //验证成功的话要把用户数据保存初始化
              this.init_current_users(res.data.object);
              sessionStorage.setItem("currentUser", JSON.stringify(res.data.object))
              //  跳转到home页面
              this.$router.push("/home")
            } else {
              //  报错
              this.$message.error(res.data.message)
            }
          })
        }
      })
    }
  }
}
</script>

<style lang="scss">
.login {
  background: url("@/assets/bannerBg.jpg");
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;

  .container {
    width: 270px;
    height: 285px;
    background: rgba(255, 255, 255, 0.075);
    border-radius: 10px;
    padding: 15px;

    .el-image {
      width: 130px !important;
      padding-bottom: 15px;

    }

    .el-button {
      color: #fff;
    }
  }
}
</style>
